<a href="https://colab.research.google.com/github/AnastasiiaDm/machine-learning/blob/main/DZ_1_numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# 1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)
a =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

In [ ]:
# 2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
a.shape

(150, 4)

In [5]:
# 3. Порахувати mean, median, standard deviation для 1-ї колонки
column_1_mean = np.mean(a[:, 0])
print(f'mean: {column_1_mean}')
column_1_median = np.median(a.T[0])
print(f'median: {column_1_median}')
deviation_1_column = np.std(a, axis=0)[0]
print(f'deviation: {deviation_1_column}')


mean: 5.843333333333334
median: 5.8
deviation: 0.8253012917851409


In [6]:
# 4. Вставити 20 значень np.nan на випадкові позиції в масиві
#   (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)
a.flat[np.random.choice(a.size, 20, replace=False)] = np.nan
a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, nan, 0.2],
       [nan, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, nan, 1.5, 0.1],
       [5.4, 3.7, nan, nan],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, nan, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
# 5. Знайти позиції вставлених значень np.nan в 1-й колонці
print(f'Nan positions in the first column: \n{np.where(np.isnan(a[:, 0]))}')

Nan positions in the first column: 
(array([  3,  42,  78, 109, 116]),)


In [8]:
# 6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)
filtered_array = a[(a[:, 2] > 1.5) & (a[:, 0] < 5.0)]
filtered_array

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [9]:
# 7. Замінити всі значення np.nan на 0
a = np.nan_to_num(a, nan=0)
a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 0. , 0.2],
       [0. , 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 0. , 1.5, 0.1],
       [5.4, 3.7, 0. , 0. ],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 0. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
# 8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю
unique_values, counts = np.unique(a, return_counts=True)
print(f"Unique values and count:\n{np.column_stack((unique_values, counts))}")


Unique values and count:
[[ 0.  20. ]
 [ 0.1  6. ]
 [ 0.2 27. ]
 [ 0.3  7. ]
 [ 0.4  7. ]
 [ 0.5  1. ]
 [ 0.6  1. ]
 [ 1.   7. ]
 [ 1.1  4. ]
 [ 1.2  7. ]
 [ 1.3 18. ]
 [ 1.4 18. ]
 [ 1.5 25. ]
 [ 1.6 11. ]
 [ 1.7  6. ]
 [ 1.8 12. ]
 [ 1.9  7. ]
 [ 2.   7. ]
 [ 2.1  6. ]
 [ 2.2  6. ]
 [ 2.3 12. ]
 [ 2.4  6. ]
 [ 2.5 11. ]
 [ 2.6  5. ]
 [ 2.7  8. ]
 [ 2.8 14. ]
 [ 2.9 10. ]
 [ 3.  24. ]
 [ 3.1 11. ]
 [ 3.2 12. ]
 [ 3.3  8. ]
 [ 3.4 12. ]
 [ 3.5  8. ]
 [ 3.6  4. ]
 [ 3.7  4. ]
 [ 3.8  7. ]
 [ 3.9  4. ]
 [ 4.   6. ]
 [ 4.1  4. ]
 [ 4.2  5. ]
 [ 4.3  2. ]
 [ 4.4  7. ]
 [ 4.5  9. ]
 [ 4.6  6. ]
 [ 4.7  7. ]
 [ 4.8  9. ]
 [ 4.9 11. ]
 [ 5.  14. ]
 [ 5.1 17. ]
 [ 5.2  6. ]
 [ 5.3  3. ]
 [ 5.4  8. ]
 [ 5.5 10. ]
 [ 5.6 12. ]
 [ 5.7 11. ]
 [ 5.8 10. ]
 [ 5.9  5. ]
 [ 6.   7. ]
 [ 6.1  9. ]
 [ 6.2  4. ]
 [ 6.3 10. ]
 [ 6.4  8. ]
 [ 6.5  4. ]
 [ 6.6  3. ]
 [ 6.7 10. ]
 [ 6.8  3. ]
 [ 6.9  5. ]
 [ 7.   1. ]
 [ 7.1  1. ]
 [ 7.2  2. ]
 [ 7.3  1. ]
 [ 7.4  1. ]
 [ 7.6  1. ]
 [ 7.7  4. ]
 [ 7.9  1. ]]

In [12]:
# 9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)
top_array_part, bottom_array_part = np.vsplit(a, 2)
print(f'Top array part:\n{top_array_part}')
print(f'Botttom array part:\n{bottom_array_part}')

Top array part:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [0.  3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 0.  1.5 0.1]
 [5.4 3.7 0.  0. ]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 0.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [0.  3.2 0.  0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  0.  0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 0.  0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

In [13]:
# 10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням
sorted_top_array_part_asc = top_array_part[top_array_part[:, 0].argsort()]
sorted_bottom_array_part_desc = bottom_array_part[bottom_array_part[:, 0].argsort()[::-1]]
print(f"Sorted top by asc: \n{sorted_top_array_part_asc}")
print(f"Sorted top by desc: \n{sorted_bottom_array_part_desc}")

Sorted top by asc: 
[[0.  3.2 0.  0.2]
 [0.  3.1 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 0.  0.2]
 [4.6 3.6 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.  0.  0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 0.  1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 2.7 3.9 1.4]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 0.  0. ]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3

In [14]:
# 11. Зібрати обидва массиви в одне ціле
np.vstack((top_array_part, bottom_array_part))

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 0. , 0.2],
       [0. , 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 0. , 1.5, 0.1],
       [5.4, 3.7, 0. , 0. ],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 0. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
# 12. Знайти найбільш часто повторюване значення в массиві
unique, indices = np.unique(a.flatten(), return_inverse=True)
most_frequent = unique[np.argmax(np.bincount(indices))]
most_frequent

0.2

In [16]:
# 13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.
def modify_column(col_index):
    return np.where(col_index < np.mean(col_index), col_index * 2, col_index / 4)


In [18]:
# 14. Застосувати отриману функцію до 3-ї колонки
col_index = 2
a[:, col_index] = modify_column(a[:, col_index])
a

array([[5.1 , 3.5 , 0.7 , 0.2 ],
       [4.9 , 3.  , 0.7 , 0.2 ],
       [4.7 , 3.2 , 0.  , 0.2 ],
       [0.  , 3.1 , 0.75, 0.2 ],
       [5.  , 3.6 , 0.7 , 0.2 ],
       [5.4 , 3.9 , 0.85, 0.4 ],
       [4.6 , 3.4 , 0.7 , 0.3 ],
       [5.  , 3.4 , 0.75, 0.2 ],
       [4.4 , 2.9 , 0.7 , 0.2 ],
       [4.9 , 0.  , 0.75, 0.1 ],
       [5.4 , 3.7 , 0.  , 0.  ],
       [4.8 , 3.4 , 0.8 , 0.2 ],
       [4.8 , 3.  , 0.7 , 0.1 ],
       [4.3 , 3.  , 0.55, 0.1 ],
       [5.8 , 4.  , 0.6 , 0.2 ],
       [5.7 , 4.4 , 0.75, 0.4 ],
       [5.4 , 3.9 , 0.65, 0.4 ],
       [5.1 , 3.5 , 0.7 , 0.3 ],
       [5.7 , 3.8 , 0.85, 0.3 ],
       [5.1 , 3.8 , 0.75, 0.3 ],
       [5.4 , 3.4 , 0.85, 0.2 ],
       [5.1 , 3.7 , 0.75, 0.4 ],
       [4.6 , 3.6 , 0.  , 0.2 ],
       [5.1 , 3.3 , 0.85, 0.5 ],
       [4.8 , 3.4 , 0.95, 0.2 ],
       [5.  , 3.  , 0.8 , 0.2 ],
       [5.  , 3.4 , 0.8 , 0.4 ],
       [5.2 , 3.5 , 0.75, 0.2 ],
       [5.2 , 3.4 , 0.7 , 0.2 ],
       [4.7 , 3.2 , 0.8 , 0.2 ],
       [4.