Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [2]:
import numpy as np

In [5]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange
arr1 = np.arange(9).reshape(3, 3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10, 5)
print(arr4)

[5 5 5 5 5 5 5 5 5 5]


In [12]:
# Завдання 5: Створити вектор з числами від 10 до 49
arr5 = np.arange(10, 50)
print(arr5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = np.flip(arr5)
print(arr6)
arr6 = arr5[::-1]
print(arr6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(81).reshape(9, 9)
print(arr7)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [31]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero
a = np.array([1,2,0,0,4,0])
arr8 = np.nonzero(a)

print(arr8)

(array([0, 1, 4]),)


In [36]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3)
print(arr9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
arr10 = np.random.rand(10)
arr10_sorted = np.sort(arr10)
print(arr10)
print(arr10_sorted)

[0.60140462 0.43177449 0.60933859 0.90298657 0.98906345 0.48754354
 0.72059605 0.28850815 0.13555167 0.11736032]
[0.11736032 0.13555167 0.28850815 0.43177449 0.48754354 0.60140462
 0.60933859 0.72059605 0.90298657 0.98906345]


In [55]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
arr11 = np.random.randint(0, 11, size=(5, 5))
print(arr11)

[[ 6 10 10  9  4]
 [ 3  2  5  5  5]
 [ 0  7  9  4 10]
 [ 1 10  3  4  7]
 [ 0 10  7  0  6]]


In [56]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = np.sum(arr11)
print(arr11_sum)

137


In [57]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = np.min(arr11)
print(arr11_min_row)

0


In [59]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = np.mean(arr11, axis=0)
print(arr11_mean_col)

[2.  7.8 6.8 4.4 6.4]


In [71]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax
arr15 = np.random.randint(10, size=15)
print(arr15)
arr15[np.argmax(arr15)] = -1
print(arr15)

[8 1 9 4 8 4 9 4 9 5 9 0 0 0 5]
[ 8  1 -1  4  8  4  9  4  9  5  9  0  0  0  5]


In [73]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
arr16 = np.random.randint(10, size=10).reshape(2, 5)
print(arr16)

[[8 7 9 6 1]
 [3 4 4 1 0]]


In [74]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = np.mean(arr16)
print(arr16_mean)

4.3
